export const CATEGORIAS = [
    { label: "AIRE ACONDICIONADO", value: "AIRE ACONDICIONADO" },
    { label: "ANAFE", value: "ANAFE" },
    { label: "ASPIRADORA", value: "ASPIRADORA" },
    { label: "BATIDORA", value: "BATIDORA" },
    { label: "CAFETERA", value: "CAFETERA" },
    { label: "CAMPANA", value: "CAMPANA" },
    { label: "COCINA", value: "COCINA" },
    { label: "FREEZER", value: "FREEZER" },
    { label: "FREIDORA", value: "FREIDORA" },
    { label: "HELADERA", value: "HELADERA" },
    { label: "HORNO", value: "HORNO" },
    { label: "LAVARROPAS", value: "LAVARROPAS" },
    { label: "LAVAVAJILLAS", value: "LAVAVAJILLAS" },
    { label: "LICUADORA", value: "LICUADORA" },
    { label: "MICROONDAS", value: "MICROONDAS" },
    { label: "MULTIPROCESADORA", value: "MULTIPROCESADORA" },
    { label: "NOTEBOOK", value: "NOTEBOOK" },
    { label: "PARRILLA ELÉCTRICA", value: "PARRILLA ELÉCTRICA" },
    { label: "PLANCHA", value: "PLANCHA" },
    { label: "PROCESADORA", value: "PROCESADORA" },
    { label: "PURIFICADOR", value: "PURIFICADOR" },
    { label: "SECARROPAS", value: "SECARROPAS" },
    { label: "SMARTPHONE", value: "SMARTPHONE" },
    { label: "TABLET", value: "TABLET" },
    { label: "TELEVISOR", value: "TELEVISOR" },
    { label: "TOSTADORA", value: "TOSTADORA" },
    { label: "VENTILADOR", value: "VENTILADOR" },
];
